services:
  - type: web
    name: appinsight-api
    runtime: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    autoDeploy: true
    healthCheckPath: /api/test
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
