<template><div ref="wrapRef" class="de-wrap"><div class="de-controls"><select v-model="pageSize" class="de-select"><option :value="10">10条/页</option><option :value="20">20条/页</option><option :value="50">50条/页</option></select><input v-model="searchText" placeholder="搜索评论..." class="de-search" @keyup.enter="loadData(1)"/><select v-model="sortBy" class="de-select"><option value="rating">按评分</option><option value="sentiment">按情感</option></select><button @click="loadData(1)" class="de-btn">查询</button></div><div v-if="loading" class="de-loading">加载中...</div><div v-else><div class="de-table-wrap"><table class="de-table"><thead><tr><th>App</th><th>领域</th><th>评分</th><th>情感</th><th>类别</th><th style="min-width:200px">评论</th></tr></thead><tbody><tr v-for="(row,i) in data" :key="i" class="de-row"><td class="de-app">{{row.app?.length>18?row.app.slice(0,18)+'...':row.app}}</td><td><span class="de-domain-tag">{{row.domain}}</span></td><td>{{'⭐'.repeat(row.rating||0)}}</td><td><span :class="row.sentiment==='positive'?'de-pos':'de-neg'">{{row.sentiment==='positive'?'正面':'负面'}}</span></td><td><span class="de-cat-tag">{{row.category}}</span></td><td class="de-text">{{(row.sentence||'').length>80?(row.sentence||'').slice(0,80)+'...':row.sentence}}</td></tr></tbody></table></div><div class="de-pagination"><button :disabled="page<=1" @click="loadData(page-1)" class="de-page-btn">← 上一页</button><span class="de-page-info">{{page}}/{{totalPages}}</span><button :disabled="page>=totalPages" @click="loadData(page+1)" class="de-page-btn">下一页 →</button><span class="de-total">共{{total}}条</span></div></div></div></template>
<script setup lang="ts">
import {ref,onMounted,watch} from 'vue'
import http from '../http'
const props=defineProps<{sentimentFilter?:string;aspectFilter?:string}>()
const wrapRef=ref<HTMLElement|null>(null); const data=ref<any[]>([]); const loading=ref(false); const page=ref(1); const totalPages=ref(1); const total=ref(0); const pageSize=ref(20); const searchText=ref(''); const sortBy=ref('rating')
async function loadData(p:number){
  page.value=p; loading.value=true
  try{const r=await http.post('/drill_down',{sentiment:props.sentimentFilter==='全部'?'all':props.sentimentFilter,category:props.aspectFilter==='全部'?'all':props.aspectFilter,search:searchText.value||undefined,sort_by:sortBy.value,page:p,page_size:pageSize.value});data.value=r.data.data||[];total.value=r.data.total||0;totalPages.value=r.data.total_pages||1}catch{}
  loading.value=false
}
onMounted(()=>loadData(1));watch(()=>[props.sentimentFilter,props.aspectFilter],()=>loadData(1))
</script>
<style scoped>
.de-wrap{padding:12px}.de-controls{display:flex;gap:10px;flex-wrap:wrap;margin-bottom:12px;align-items:center}.de-select,.de-search{padding:7px 12px;border:1px solid #e2e8f0;border-radius:8px;font-size:12px;font-family:inherit;outline:none;background:#fff}.de-select:focus,.de-search:focus{border-color:#2563eb}.de-search{flex:1;min-width:150px}.de-btn{padding:7px 18px;background:#2563eb;color:#fff;border:none;border-radius:8px;font-size:12px;cursor:pointer;font-family:inherit}.de-btn:hover{background:#1d4ed8}.de-loading{text-align:center;color:#94a3b8;padding:40px}.de-table-wrap{overflow-x:auto;border:1px solid #e2e8f0;border-radius:10px}.de-table{width:100%;border-collapse:collapse;font-size:12px}.de-table th{background:#f8fafc;padding:10px 12px;text-align:left;font-weight:600;color:#475569;border-bottom:1px solid #e2e8f0}.de-table td{padding:9px 12px;border-bottom:1px solid #f1f5f9;color:#334155}.de-row:hover{background:#f8fafc}.de-app{font-weight:500;color:#0f172a}.de-domain-tag{padding:2px 8px;background:#eef2ff;color:#4f46e5;border-radius:4px;font-size:11px}.de-pos{padding:2px 8px;border-radius:4px;font-size:11px;font-weight:500;background:#f0fdf4;color:#16a34a}.de-neg{padding:2px 8px;border-radius:4px;font-size:11px;font-weight:500;background:#fef2f2;color:#dc2626}.de-cat-tag{padding:2px 8px;background:#f1f5f9;color:#64748b;border-radius:4px;font-size:11px}.de-text{color:#64748b;font-size:11px;max-width:250px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.de-pagination{display:flex;align-items:center;gap:12px;justify-content:center;margin-top:16px}.de-page-btn{padding:6px 14px;border:1px solid #e2e8f0;border-radius:6px;background:#fff;font-size:12px;cursor:pointer;font-family:inherit;color:#475569}.de-page-btn:disabled{opacity:0.4;cursor:default}.de-page-btn:hover:not(:disabled){border-color:#2563eb;color:#2563eb}.de-page-info{font-size:12px;color:#64748b;font-weight:600}.de-total{font-size:11px;color:#94a3b8;margin-left:8px}
</style>
