<template><div ref="wrapRef" class="nps-wrap"><div v-if="loading" class="nps-loading">加载中...</div><template v-else><div class="nps-score-row"><div class="nps-big">{{ npsData.nps_score > 0 ? '+' : '' }}{{ npsData.nps_score }}</div><div class="nps-lbl">NPS 净推荐值 · 样本量 {{ npsData.total }}</div></div><div class="nps-scale"><div class="nps-scale-negative"></div><div class="nps-scale-neutral"></div><div class="nps-scale-positive"></div><span class="nps-marker" :style="{ left: `${Math.max(0, Math.min(100, (npsData.nps_score + 100) / 2))}%` }"><i></i><strong>{{ npsData.nps_score > 0 ? '+' : '' }}{{ npsData.nps_score }}</strong></span></div><div class="nps-scale-labels"><span>-100 贬损</span><span>0 中性</span><span>+100 推荐</span></div><div class="nps-breakdown"><div><i class="nps-dot nps-dot-detractor"></i><strong>{{ npsData.detractor_rate }}%</strong><span>贬损者</span></div><div><i class="nps-dot nps-dot-passive"></i><strong>{{ npsData.passive_rate }}%</strong><span>被动者</span></div><div><i class="nps-dot nps-dot-promoter"></i><strong>{{ npsData.promoter_rate }}%</strong><span>推荐者</span></div></div></template></div></template>
<script setup lang="ts">
import {ref,reactive,onMounted,watch} from 'vue'
import http from '../http'
const props=defineProps<{sentimentFilter?:string;aspectFilter?:string}>()
const wrapRef=ref<HTMLElement|null>(null); const loading=ref(true)
const npsData=reactive({nps_score:0,promoters:0,passives:0,detractors:0,total:0,promoter_rate:0,passive_rate:0,detractor_rate:0})
async function load(){
  loading.value=true
  try{const r=await http.post('/nps',{sentiment:props.sentimentFilter==='全部'?'all':props.sentimentFilter,category:props.aspectFilter==='全部'?'all':props.aspectFilter});Object.assign(npsData,r.data)}catch{}
  loading.value=false
}
onMounted(load);watch(()=>[props.sentimentFilter,props.aspectFilter],load)
</script>
<style scoped>
.nps-wrap{padding:22px 24px 24px;text-align:center}.nps-loading{text-align:center;color:var(--text-faint);padding:40px}.nps-score-row{margin-bottom:24px}.nps-big{font-family:var(--font-mono);font-size:48px;font-weight:800;line-height:1;color:var(--ink)}.nps-lbl{font-size:11px;color:var(--text-muted);margin-top:7px}.nps-scale{position:relative;display:flex;height:12px;overflow:visible;border-radius:99px;background:var(--neutral-soft)}.nps-scale-negative{flex:1;background:var(--negative);border-radius:99px 0 0 99px;opacity:.8}.nps-scale-neutral{width:8%;background:var(--warning);opacity:.8}.nps-scale-positive{flex:1;background:var(--positive);border-radius:0 99px 99px 0;opacity:.8}.nps-marker{position:absolute;top:-9px;display:flex;align-items:center;flex-direction:column;transform:translateX(-50%);color:var(--ink);font-family:var(--font-mono);font-size:10px}.nps-marker i{width:3px;height:30px;border-radius:3px;background:var(--ink);box-shadow:0 0 0 3px rgba(255,255,255,.92)}.nps-marker strong{position:absolute;top:-20px;white-space:nowrap}.nps-scale-labels{display:flex;justify-content:space-between;margin-top:11px;color:var(--text-faint);font-family:var(--font-mono);font-size:9px}.nps-breakdown{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-top:25px;padding-top:15px;border-top:1px solid var(--line)}.nps-breakdown>div{display:flex;align-items:center;justify-content:center;gap:5px;flex-wrap:wrap}.nps-breakdown strong{font-family:var(--font-mono);font-size:13px;color:var(--ink)}.nps-breakdown span{width:100%;color:var(--text-faint);font-size:10px}.nps-dot{width:7px;height:7px;border-radius:50%}.nps-dot-detractor{background:var(--negative)}.nps-dot-passive{background:var(--warning)}.nps-dot-promoter{background:var(--positive)}
</style>
